apiVersion: v1
kind: Service
metadata:
  name: push
spec:
  type: NodePort
  ports:
    - name: web
      port: 5701
      targetPort: 5701
  selector:
    app: push
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: push
spec:
  selector:
    matchLabels:
      app: push
  replicas: 1
  template:
    metadata:
      labels:
        app: push
    spec:
      containers:
        - name: push
          image: fish.co:5000/push:0.0.1
          imagePullPolicy: IfNotPresent
          args:
            ["server"]
          volumeMounts:
          - name: config
            mountPath: /home/www/push/config.js
            subPath: config.js
          ports:
            - containerPort: 5701
          env:
            - name: TZ
              value: 'Asia/Shanghai'
      dnsPolicy: Default
      volumes:
      - name: config
        configMap:
          name: push-cfg
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: push-cfg
  labels:
    app: push
data:
  config.js: |
    exports.ups = [
      {
        'type': 1,
        'userID': 7005405,
        'username': '海猫umi',
        'groupQQ': 1109738985,
      },
      {
        'type': 1,
        'userID': 36782454,
        'username': '可可啦',
        'groupQQ': 577202845,
      },
      {
        'type': 2,
        'userID': 5339362,
        'liveRoomID': 5339362,
        'username': '女宅',
        'groupQQ': 1577034,
      },
    ]
