apiVersion: v1
kind: Service
metadata:
  name: push
spec:
  type: NodePort
  ports:
    - name: web
      port: 5701
      targetPort: 5701
  selector:
    app: push
---
apiVersion: v1
kind: Deployment
metadata:
  name: push
spec:
  selector:
    matchLabels:
      app: push
  replicas: 1
  template:
    metadata:
      labels:
        app: push
    spec:
      containers:
        - name: push
          image: 127.0.0.1:5000/push:0.0.1
          imagePullPolicy: IfNotPresent
          args:
            ["server"]
          # volumeMounts:
          #  - name: config
          #    mountPath: /home/www/push/config.js
          #    subPath: config.js
          ports:
            - containerPort: 5701
          env:
            - name: TZ
              value: 'Asia/Shanghai'
      #volumes:
      #  - name: config
      #    configMap:
      #      name: node-web-cfg
