apiVersion: v1
kind: Service
metadata:
  name: push
spec:
  type: NodePort
  ports:
  - name: web
    port: 5701
    targetPort: 5701
  selector:
    app: push
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: push
spec:
  selector:
    matchLabels:
      app: push
  replicas: 1
  template:
    metadata:
      labels:
        app: push
    spec:
      containers:
      - name: push
        image: fish.co:5000/push:0.1.2-4
        imagePullPolicy: IfNotPresent
        args:
          ["server"]
        volumeMounts:
        - name: config
          mountPath: /home/www/push/config.js
          subPath: config.js
        ports:
        - containerPort: 5701
        env:
        - name: TZ
          value: 'Asia/Shanghai'
      dnsPolicy: Default
      volumes:
      - name: config
        configMap:
          name: push-cfg
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: push-cfg
  labels:
    app: push
data:
  config.js: |
    exports.Tulin = {
      'apiKey': "xxxxx",
      'userId': "xxxxxx",
    }
    exports.qqSerice = 'http://10.97.19.249:5700/'
    exports.mysql = {
      host     : '127.0.0.1',
      user     : 'test',
      password : 'test',
      port: '3306',
      database: 'music',
    }
    exports.paths = {
      acfunLive: './.runtime/acfunLive/',
    }
    exports.aliyun = {
      oss: {
        publicUrl: 'http://s1.acgay.cn/',
        region: 'oss-cn-hangzhou',
        internal: false,
        secure: false,
        bucket: 'acgay',
        timeout: 3600000,
        accessKeyId: 'test',
        accessKeySecret: 'test',
      },
    }
    exports.qqBot = {
      url: 'http://127.0.0.1:5700/',
      botQQ: 123456,
    }
    exports.acfun = {
      cookie: 'acfun cookie',
      liveDid: 'acfun cookie did',
    }

